name: Autogen

on:
  workflow_dispatch:
    inputs:
      payload:
        required: true
        description: 'Direct URL to autogen payload zip'

permissions:
  contents: write

jobs:
  autogen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Fetch payload
        run: |
          mkdir -p ./autogen/input/
          curl -fL# "${{ inputs.payload }}" -o ./autogen/input/payload.zip

      - name: Unzip payload
        run: |
          unzip -o ./autogen/input/payload.zip -d ./autogen/input/
          rm ./autogen/input/payload.zip

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xmlstarlet

      - name: Run autogen
        run: ./autogen/generate

      - name: Compress outputs
        run: zip -vr9 ./autogen/output/output.zip ./autogen/output/*

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ludere-autogen-${{ steps.date.outputs.date }}
          name: Ludere Autogen ${{ steps.date.outputs.date }}
          files: ./autogen/output/output.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
